/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package cafemanagementsystem;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author thuan
 */
public class Account extends javax.swing.JInternalFrame {
    public String userEmail;
    /**
     * Creates new form Product
     */
    public Account() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    public Account(String email) {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        
        userEmail = email;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnChangePassword = new javax.swing.JLabel();
        btnChangeSecurityQuestion = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnChangePassword.setBackground(new java.awt.Color(255, 255, 255));
        btnChangePassword.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnChangePassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/popupicon/password_30px.png"))); // NOI18N
        btnChangePassword.setText("Thay đổi mật khẩu");
        btnChangePassword.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(25, 118, 211)));
        btnChangePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChangePasswordMouseClicked(evt);
            }
        });
        jPanel1.add(btnChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 270, 60));

        btnChangeSecurityQuestion.setBackground(new java.awt.Color(255, 255, 255));
        btnChangeSecurityQuestion.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnChangeSecurityQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnChangeSecurityQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/popupicon/ask_question_30px.png"))); // NOI18N
        btnChangeSecurityQuestion.setText("Thay đổi câu hỏi bảo mật");
        btnChangeSecurityQuestion.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(25, 118, 211)));
        btnChangeSecurityQuestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangeSecurityQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChangeSecurityQuestionMouseClicked(evt);
            }
        });
        jPanel1.add(btnChangeSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 280, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePasswordMouseClicked
        // TODO add your handling code here:
        ChangePassword changePassword = new ChangePassword(userEmail);
        changePassword.setVisible(true);

    }//GEN-LAST:event_btnChangePasswordMouseClicked

    private void btnChangeSecurityQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeSecurityQuestionMouseClicked
        // TODO add your handling code here:
        ChangeSecurityQuestion changeSecurityQuestion = new ChangeSecurityQuestion(userEmail);
        changeSecurityQuestion.setVisible(true);

    }//GEN-LAST:event_btnChangeSecurityQuestionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnChangePassword;
    private javax.swing.JLabel btnChangeSecurityQuestion;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
